cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://netcodeblab.dd:8083/themes/custom/netcodec/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  netcodec: 8000
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://netcodec_small_1.png'
  url: ''
  use_default: false
fluid_container: 1
table_responsive: '-1'
table: ''
